[package]
name = "dup-indexer"
version = "0.1.0"
description = "Create a non-duplicated index from Strings, static str, Vec, or Box values"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
repository = "https://github.com/nyurik/dup-indexer"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
