name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            set -x
            rustc --version
            cargo --version
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
            cargo test --doc

  miri:
    name: Miri Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install miri
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri
          override: true
      - run: |
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            set -x
            rustc --version
            cargo --version
            cargo miri test
