name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            source .cargo-husky/hooks/pre-push

  miri:
    name: Miri Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install miri
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri
          override: true
      - run: |
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            set -ex
            rustc --version
            cargo --version
            cargo miri test
